In [6]:
import pandas as pd
import numpy as np
from connect_to_mysql import Database
import MySQLdb as my
import mysql.connector

In [7]:
df = pd.read_excel(
    # "/Users/ericchittka/rides_combined.csv"
    "C:/Users/jostm7/Desktop/Uni Mannheim/2. Semester/Teamprojekt/vehicle-stream-team-project/data/cleaning/test_1651761611.xlsx"
)
# df.drop(labels=['Unnamed: 0','index'], axis=1,inplace=True)
df = df.iloc[0:20]
df.columns

Index(['Unnamed: 0', 'id', 'user_id', 'distance', 'number_of_passenger',
       'price_operations', 'price_offer', 'price_payed', 'free_ride',
       'payment_type', 'pickup_address', 'dropoff_address', 'state',
       'created_from_offer', 'created_at', 'scheduled_to', 'dispatched_at',
       'pickup_arrival_time', 'arriving_push', 'vehicle_arrived_at',
       'earliest_pickup_expectation', 'pickup_first_eta', 'pickup_eta',
       'pickup_at', 'dropoff_first_eta', 'dropoff_eta', 'dropoff_at',
       'updated_at', 'arrival_deviation', 'waiting_time', 'boarding_time',
       'ride_time', 'trip_time', 'shortest_ridetime', 'delay',
       'longer_route_factor', 'arrival_indicator', 'rating',
       'rating_puenktlichkeit', 'rating_sauberkeit', 'rating_fahrer',
       'rating_find_modstop', 'rating_other_comments', 'cancellation_reason',
       'cancellation_comment', 'bahn_card_number', 'year_card_type',
       'year_card_number', 'canceled_at', 'rating_question_one',
       'rating_question_two', 'index'],
      dtype='object')

In [8]:
df.head()

,Unnamed: 0,id,user_id,distance,number_of_passenger,price_operations,price_offer,price_payed,free_ride,payment_type,...,rating_other_comments,cancellation_reason,cancellation_comment,bahn_card_number,year_card_type,year_card_number,canceled_at,rating_question_one,rating_question_two,index
0,0,5727475e-8224-4302-9228-c92b9d4a5220,f8ff0526-887a-4e48-ad96-977e12fd70c1,5483,1.0,4.65,4.65,0.00,0.0,STANDARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,18fec0a6-b7ba-442b-8472-04bdb6ba1b86,51e1a1a8-995c-488c-84ce-3789e46f0417,3575,1.0,0.00,2.77,0.00,0.0,BAHN_CARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,bb916271-0627-4196-8ec1-5324e0e1f71d,f07028da-ca7e-4713-9e45-743c71712e80,3040,1.0,3.45,1.55,1.55,0.0,VRN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3cffa0f3-e278-4828-b0a1-f55cb35c1adb,44f61d06-8e79-42c6-9abd-0e85fcaf9d6d,7233,1.0,0.00,5.55,0.00,1.0,STANDARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2965,1a6d2ec4-7e85-4e5b-aed0-1c3693268986,3998,NaN,NaN,NaN,NaN,NaN,STANDARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
Database.insert_dataframe(df,'rides')

Dropped columns ['Unnamed: 0', 'index'] from input df
Replaced NaN by None
Commit Succesful

In [10]:
query_df = Database.query_dataframe('rides')
query_df

,db_updated_at,id,user_id,distance,number_of_passenger,price_operations,price_offer,price_payed,free_ride,payment_type,...,rating,rating_puenktlichkeit,rating_sauberkeit,rating_fahrer,rating_find_modstop,rating_other_comments,rating_question_one,rating_question_two,cancellation_reason,cancellation_comment
0,None,0f12f88d-00b8-4bb3-a231-683117c0b075,f07028da-ca7e-4713-9e45-743c71712e80,3040,1.0,3.45,1.55,1.55,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
1,None,12011bcd-9ee9-4d1a-aba2-b3a5f9097a53,d2a75ace-8b9f-4b32-9914-85e434ce9019,3048,1.0,3.45,3.45,3.45,0.0,STANDARD,...,None,None,None,None,None,None,None,None,None,None
2,None,18fec0a6-b7ba-442b-8472-04bdb6ba1b86,51e1a1a8-995c-488c-84ce-3789e46f0417,3575,1.0,0.00,2.77,0.00,0.0,BAHN_CARD,...,None,None,None,None,None,None,None,None,None,None
3,None,1dc450cc-7640-4c71-860b-827a64a3b9e6,c7348715-229b-46ce-8ccf-bd9fa10af015,6257,1.0,5.05,2.95,2.95,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
4,None,2965,1a6d2ec4-7e85-4e5b-aed0-1c3693268986,3998,NaN,NaN,NaN,NaN,NaN,STANDARD,...,None,None,None,None,None,None,None,None,None,None
5,None,2966,2c172cdf-dd04-4613-9073-9517adef0138,8109,NaN,NaN,NaN,NaN,NaN,STANDARD,...,None,None,None,None,None,None,None,None,None,None
6,None,2970,181628b6-2ecd-4368-bcaa-c9e38162dc57,6025,NaN,NaN,NaN,NaN,NaN,BAHN_CARD,...,None,None,None,None,None,None,None,None,None,None
7,None,2971,181628b6-2ecd-4368-bcaa-c9e38162dc57,6025,NaN,NaN,NaN,NaN,NaN,BAHN_CARD,...,None,None,None,None,None,None,None,None,None,None
8,None,3cffa0f3-e278-4828-b0a1-f55cb35c1adb,44f61d06-8e79-42c6-9abd-0e85fcaf9d6d,7233,1.0,0.00,5.55,0.00,1.0,STANDARD,...,None,None,None,None,None,None,None,None,None,None
9,None,5727475e-8224-4302-9228-c92b9d4a5220,f8ff0526-887a-4e48-ad96-977e12fd70c1,5483,1.0,4.65,4.65,0.00,0.0,STANDARD,...,None,None,None,None,None,None,None,None,None,None
10,None,58744ff5-617c-4d8f-912c-1b702e602fec,f07028da-ca7e-4713-9e45-743c71712e80,3040,1.0,3.45,1.55,1.55,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
11,None,5b9be6cf-1b25-43d7-b077-e0ede60ba49a,f07028da-ca7e-4713-9e45-743c71712e80,3040,1.0,3.45,1.55,1.55,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
12,None,72d3d151-aefc-44c8-bfa6-26fc8b0d00a9,c38d774c-1972-4a95-824d-23ad56cade88,5231,3.0,9.85,7.75,7.75,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
13,None,7a8d19a9-8985-4006-a5bd-be821b43ccff,c7348715-229b-46ce-8ccf-bd9fa10af015,6257,1.0,5.05,2.95,2.95,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
14,None,8848219a-e3d6-4ed7-ba9d-3159a2870630,b6537f08-519c-4c67-ad43-6996aca5fb9a,2078,1.0,0.00,2.95,0.00,0.0,STANDARD,...,None,None,None,None,None,None,None,None,None,None
15,None,90ef7121-ff20-40bb-9489-f9e935519443,7b093b19-1bc2-4bc0-b9cb-fcb8cfb8f074,5974,1.0,4.90,2.80,2.80,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
16,None,95ec2460-b9f8-49ff-8ac6-e33a9b9afbad,b55368d0-7774-4e8a-9a58-6c283a92072f,4302,1.0,4.10,2.40,2.40,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
17,None,bb916271-0627-4196-8ec1-5324e0e1f71d,f07028da-ca7e-4713-9e45-743c71712e80,3040,1.0,3.45,1.55,1.55,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
18,None,f797b4d6-2fd4-442a-aec3-32c7f34c9b3e,7b093b19-1bc2-4bc0-b9cb-fcb8cfb8f074,6511,1.0,5.20,3.10,3.10,0.0,VRN,...,None,None,None,None,None,None,None,None,None,None
19,None,f9746493-25b9-40fc-bd1e-87d458abfad9,729c1dee-ab62-43a2-abf9-5e6320fb2338,2223,1.0,3.05,3.05,3.05,0.0,STANDARD,...,None,None,None,None,None,None,None,None,None,None

In [11]:
query_df = Database.query_dataframe('rides','select id from rides')
query_df

                                      id
0   12011bcd-9ee9-4d1a-aba2-b3a5f9097a53
1   1dc450cc-7640-4c71-860b-827a64a3b9e6
2   72d3d151-aefc-44c8-bfa6-26fc8b0d00a9
3                                   2970
4                                   2971
5   f797b4d6-2fd4-442a-aec3-32c7f34c9b3e
6   f9746493-25b9-40fc-bd1e-87d458abfad9
7   18fec0a6-b7ba-442b-8472-04bdb6ba1b86
8   95ec2460-b9f8-49ff-8ac6-e33a9b9afbad
9                                   2965
10  7a8d19a9-8985-4006-a5bd-be821b43ccff
11  90ef7121-ff20-40bb-9489-f9e935519443
12  8848219a-e3d6-4ed7-ba9d-3159a2870630
13  58744ff5-617c-4d8f-912c-1b702e602fec
14  5b9be6cf-1b25-43d7-b077-e0ede60ba49a
15                                  2966
16  0f12f88d-00b8-4bb3-a231-683117c0b075
17  bb916271-0627-4196-8ec1-5324e0e1f71d
18  5727475e-8224-4302-9228-c92b9d4a5220
19  3cffa0f3-e278-4828-b0a1-f55cb35c1adb